name: foodai
channels:
  - defaults
dependencies:
  - alabaster
  - appnope
  - asn1crypto
  - babel
  - bleach
  - ca-certificates
  - cctools
  - certifi
  - cffi
  - chardet
  - clang
  - clang_osx-64
  - clangxx
  - clangxx_osx-64
  - compiler-rt
  - cryptography
  - cycler
  - decorator
  - docutils
  - entrypoints
  - freetype
  - h5py
  - hdf5
  - html5lib
  - idna
  - imagesize
  - intel-openmp
  - ipykernel
  - ipython
  - ipython-notebook
  - ipython_genutils
  - jedi
  - jinja2
  - jsonschema
  - jupyter_client
  - jupyter_core
  - keras
  - kiwisolver
  - ld64
  - libcxx
  - libcxxabi
  - libedit
  - libffi
  - libgfortran
  - libpng
  - libprotobuf
  - libsodium
  - llvm
  - llvm-lto-tapi
  - markupsafe
  - matplotlib
  - mistune
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - nbconvert
  - nbformat
  - ncurses
  - notebook
  - numpy
  - numpydoc
  - openssl
  - packaging
  - pandoc
  - pandocfilters
  - parso
  - pexpect
  - pickleshare
  - pip
  - prompt_toolkit
  - protobuf
  - ptyprocess
  - pycparser
  - pygments
  - pyopenssl
  - pyparsing
  - pysocks
  - python
  - python-dateutil
  - pytz
  - pyyaml
  - pyzmq
  - readline
  - requests
  - scipy
  - send2trash
  - setuptools
  - simplegeneric
  - six
  - snowballstemmer
  - sphinx
  - sphinxcontrib
  - sphinxcontrib-websupport
  - sqlite
  - tensorflow
  - terminado
  - testpath
  - theano
  - tk
  - tornado
  - traitlets
  - typing
  - urllib3
  - wcwidth
  - webencodings
  - werkzeug
  - wheel
  - xz
  - yaml
  - zeromq
  - zlib